
-- Run this in your Supabase SQL Editor

-- 1. Create table for tracking created games
CREATE TABLE IF NOT EXISTS games_created (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL,
    creator_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Create table for tracking played games
CREATE TABLE IF NOT EXISTS games_played (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL,
    played_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Create table for tracking completed games (wins/losses)
CREATE TABLE IF NOT EXISTS games_completed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id TEXT NOT NULL,
    is_win BOOLEAN DEFAULT FALSE,
    attempts INTEGER DEFAULT 1,
    completed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 4. Enable Row Level Security (RLS) - Required by Supabase
ALTER TABLE games_created ENABLE ROW LEVEL SECURITY;
ALTER TABLE games_played ENABLE ROW LEVEL SECURITY;
ALTER TABLE games_completed ENABLE ROW LEVEL SECURITY;

-- 5. Create policies to allow ANYONE (anon) to INSERT data
-- Drop policies if they exist to prevent errors on re-run
DROP POLICY IF EXISTS "Enable insert for all users" ON games_created;
DROP POLICY IF EXISTS "Enable insert for all users" ON games_played;
DROP POLICY IF EXISTS "Enable insert for all users" ON games_completed;
DROP POLICY IF EXISTS "Enable insert for all users" ON visitor_logs;

CREATE POLICY "Enable insert for all users" ON games_created FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for all users" ON games_played FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for all users" ON games_completed FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for all users" ON visitor_logs FOR INSERT WITH CHECK (true);

-- 6. Create policies to allow ONLY AUTHENTICATED users to READ data
DROP POLICY IF EXISTS "Enable read for all users" ON games_created;
DROP POLICY IF EXISTS "Enable read for all users" ON games_played;
DROP POLICY IF EXISTS "Enable read for all users" ON games_completed;
DROP POLICY IF EXISTS "Enable read for all users" ON visitor_logs;

CREATE POLICY "Enable read for authenticated users only" ON games_created FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read for authenticated users only" ON games_played FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read for authenticated users only" ON games_completed FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable read for authenticated users only" ON visitor_logs FOR SELECT TO authenticated USING (true);


-- 7. (NEW) Update visitor_logs table with location columns
-- Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS visitor_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_url TEXT,
    user_agent TEXT,
    country TEXT,
    city TEXT,
    visited_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Add columns if they don't exist (for existing tables)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'visitor_logs' AND column_name = 'country') THEN
        ALTER TABLE visitor_logs ADD COLUMN country TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'visitor_logs' AND column_name = 'city') THEN
        ALTER TABLE visitor_logs ADD COLUMN city TEXT;
    END IF;
END $$;

-- 8. (NEW) Create table for Game Storage (Persistent)
-- Using JSONB for game_data allows us to store the entire Game object 
-- without needing to create columns for every single field.
CREATE TABLE IF NOT EXISTS games (
    id TEXT PRIMARY KEY, -- We use the generated string ID
    game_data JSONB NOT NULL, -- Stores the entire Game object
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE games ENABLE ROW LEVEL SECURITY;

-- Allow anyone to create a game (INSERT)
CREATE POLICY "Enable insert for all users" ON games FOR INSERT WITH CHECK (true);

-- Allow anyone to read a game (SELECT) - needed for playing
CREATE POLICY "Enable read for all users" ON games FOR SELECT USING (true);


